<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="360NDCLP063" ignored="0" name="Demo CRM Testcase" tests="11" failures="1" timestamp="2020-06-22T15:55:22 IST" time="225.873" errors="0">
  <testcase name="TestClassicCRM" time="4.125" classname="com.crm.qa.test.LoginTest"/>
  <testcase name="TestForgotPassword" time="7.348" classname="com.crm.qa.test.LoginTest"/>
  <testcase name="TestInvalidLogin" time="0.908" classname="com.crm.qa.test.LoginTest"/>
  <testcase name="TestSignUp" time="6.456" classname="com.crm.qa.test.LoginTest"/>
  <testcase name="TestValidLogin" time="3.159" classname="com.crm.qa.test.LoginTest"/>
  <testcase name="verifyLoginPageTitle" time="0.016" classname="com.crm.qa.test.LoginTest"/>
  <testcase name="clickOnMenu" time="2.572" classname="com.crm.qa.test.HomeTest"/>
  <testcase name="validateHomePage" time="0.015" classname="com.crm.qa.test.HomeTest">
    <failure type="java.lang.AssertionError" message="expected [https://ui.cogmento.com/home] but found [https://ui.cogmento.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://ui.cogmento.com/home] but found [https://ui.cogmento.com/]
at com.crm.qa.test.HomeTest.validateHomePage(HomeTest.java:38)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- validateHomePage -->
  <testcase name="validateMenuList" time="3.031" classname="com.crm.qa.test.HomeTest"/>
  <testcase name="validateUser" time="1.112" classname="com.crm.qa.test.HomeTest"/>
  <testcase name="ValidateContactsPage_NoRecords" time="0.708" classname="com.crm.qa.test.ContactsTest"/>
</testsuite> <!-- Demo CRM Testcase -->
